import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,collection,getDocs,addDoc,doc,updateDoc,deleteDoc,getDoc,setDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";import{getStorage,ref,uploadBytes,getDownloadURL}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js";
const firebaseConfig={apiKey:"AIzaSyCsS0rR0wOz3mGBszmtKwPXQZi4pFVcukA",authDomain:"cafemenu-3ff9a.firebaseapp.com",projectId:"cafemenu-3ff9a",storageBucket:"cafemenu-3ff9a.firebasestorage.app",messagingSenderId:"52378316579",appId:"1:52378316579:web:8512b57f8a9c6f64b8a696"};const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app);let cats=[],prods=[],editId=null,editType=null;const $=x=>document.getElementById(x),ph="https://placehold.co/900x600?text=CafeMenu";
$("loginForm").onsubmit=async e=>{e.preventDefault();$("err").textContent="";try{await signInWithEmailAndPassword(auth,$("email").value,$("password").value)}catch(e){$("err").textContent="البريد أو كلمة المرور غير صحيحة"}};$("logout").onclick=()=>signOut(auth);
onAuthStateChanged(auth,u=>{if(u){$("login").classList.add("hidden");$("app").classList.remove("hidden");load()}else{$("app").classList.add("hidden");$("login").classList.remove("hidden")}});
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(b.dataset.page).classList.remove("hidden");$("title").textContent=b.textContent});
async function load(){cats=(await getDocs(collection(db,"categories"))).docs.map(d=>({id:d.id,...d.data()}));prods=(await getDocs(collection(db,"products"))).docs.map(d=>({id:d.id,...d.data()}));render();let s=await getDoc(doc(db,"settings","restaurant"));if(s.exists()){let x=s.data();$("rname").value=x.restaurantName||"";$("wa").value=x.whatsapp||"";$("phone").value=x.phone||"";$("address").value=x.address||"";$("hours").value=x.hours||""}}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function render(){$("sc").textContent=cats.length;$("sp").textContent=prods.length;$("sa").textContent=prods.filter(x=>x.available!==false).length;$("sf").textContent=prods.filter(x=>x.featured).length;$("catGrid").innerHTML=cats.map(c=>`<div class="card"><img src="${esc(c.image||ph)}"><h3>${esc(c.name)}</h3><p>${prods.filter(x=>x.categoryId===c.id).length} أصناف</p><div class="actions"><button onclick="editCat('${c.id}')">تعديل</button><button class="danger" onclick="delCat('${c.id}')">حذف</button></div></div>`).join("")||"<div class=panel>لا توجد أقسام بعد.</div>";$("prodGrid").innerHTML=prods.map(p=>`<div class=card><img src="${esc(p.image||ph)}"><h3>${esc(p.name)} — ${p.price} ₪</h3><p>${esc(p.description||"")}</p><span class=status>${p.available!==false?"متوفر":"غير متوفر"}</span><div class=actions><button onclick="editProd('${p.id}')">تعديل</button><button class=danger onclick="delProd('${p.id}')">حذف</button></div></div>`).join("")||"<div class=panel>لا توجد أصناف بعد.</div>"}
window.categoryModal=()=>{editId=null;editType="cat";$("mtitle").textContent="إضافة قسم";$("form").innerHTML=`<label>اسم القسم<input id=fname required></label><label>رابط الصورة<input id=fimage placeholder="https://..."></label><label>أو اختر صورة من جهازك<input id=ffile type=file accept=image/*></label><img id=prev class=preview src=${ph}><button>حفظ</button>`;$("modal").classList.remove("hidden");preview()};
window.productModal=()=>{editId=null;editType="prod";$("mtitle").textContent="إضافة صنف";$("form").innerHTML=prodForm({});$("modal").classList.remove("hidden");preview()};
function prodForm(p){return`<label>اسم الصنف<input id=fname required value="${esc(p.name||"")}"></label><label>القسم<select id=fcat required>${cats.map(c=>`<option value=${c.id} ${p.categoryId===c.id?"selected":""}>${esc(c.name)}</option>`).join("")}</select></label><label>السعر ₪<input id=fprice type=number min=0 step=.01 required value="${p.price??""}"></label><label>الوصف<textarea id=fdesc>${esc(p.description||"")}</textarea></label><label>رابط الصورة<input id=fimage value="${esc(p.image||"")}" placeholder="https://..."></label><label>أو اختر صورة من جهازك<input id=ffile type=file accept=image/*></label><img id=prev class=preview src="${esc(p.image||ph)}"><label class=check><input id=favail type=checkbox ${p.available!==false?"checked":""}> متوفر</label><label class=check><input id=ffeat type=checkbox ${p.featured?"checked":""}> ⭐ الأكثر طلباً</label><label class=check><input id=foffer type=checkbox ${p.offer?"checked":""}> 🔥 عرض خاص</label><button>حفظ</button>`}
function preview(){let f=$("ffile"),u=$("fimage"),p=$("prev");if(f)f.onchange=()=>{if(f.files[0])p.src=URL.createObjectURL(f.files[0])};if(u)u.oninput=()=>{if(u.value)p.src=u.value}}
window.editCat=id=>{let c=cats.find(x=>x.id===id);editId=id;editType="cat";$("mtitle").textContent="تعديل قسم";$("form").innerHTML=`<label>اسم القسم<input id=fname required value="${esc(c.name)}"></label><label>رابط الصورة<input id=fimage value="${esc(c.image||"")}"></label><label>اختر صورة<input id=ffile type=file accept=image/*></label><img id=prev class=preview src="${esc(c.image||ph)}"><button>حفظ</button>`;$("modal").classList.remove("hidden");preview()};
window.editProd=id=>{let p=prods.find(x=>x.id===id);editId=id;editType="prod";$("mtitle").textContent="تعديل صنف";$("form").innerHTML=prodForm(p);$("modal").classList.remove("hidden");preview()};
window.closeModal=()=>{$("modal").classList.add("hidden")};
$("form").onsubmit=async e=>{e.preventDefault();try{let image=$("fimage").value.trim(),file=$("ffile")?.files?.[0];if(file){let r=ref(storage,`menu/${auth.currentUser.uid}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`);await uploadBytes(r,file);image=await getDownloadURL(r)}if(editType==="cat"){let d={name:$("fname").value.trim(),image,updatedAt:serverTimestamp()};editId?await updateDoc(doc(db,"categories",editId),d):await addDoc(collection(db,"categories"),{...d,createdAt:serverTimestamp()})}else{let d={name:$("fname").value.trim(),categoryId:$("fcat").value,price:Number($("fprice").value),description:$("fdesc").value.trim(),image,available:$("favail").checked,featured:$("ffeat").checked,offer:$("foffer").checked,updatedAt:serverTimestamp()};editId?await updateDoc(doc(db,"products",editId),d):await addDoc(collection(db,"products"),{...d,createdAt:serverTimestamp()})}closeModal();await load()}catch(e){alert("حدث خطأ: "+e.message)}};
window.delCat=async id=>{if(confirm("حذف القسم؟")){await deleteDoc(doc(db,"categories",id));load()}};window.delProd=async id=>{if(confirm("حذف الصنف؟")){await deleteDoc(doc(db,"products",id));load()}};
$("settingsForm").onsubmit=async e=>{e.preventDefault();await setDoc(doc(db,"settings","restaurant"),{restaurantName:$("rname").value,whatsapp:$("wa").value,phone:$("phone").value,address:$("address").value,hours:$("hours").value,updatedAt:serverTimestamp()},{merge:true});alert("تم الحفظ")};